### PR TITLE
Fix dependencies parsing error

### LINKED ISSUE #44: Broken with GitHub actions current default version of ruby and/or Bundler
I see an infinite (until timeout) loop of:
```
 2024-06-16 14:09:56 +0000 W [      info] [NoMethodError] /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:265:in `process_element': undefined method `dependencies' for an instance of Bundler::CompactIndexClient::Cache (NoMethodError)
        info = cic.instance_variable_get(:@cache).dependencies(name)
                                                 ^^^^^^^^^^^^^
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:249:in `block in process_collection'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:248:in `delete_if'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:248:in `process_collection'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:60:in `block in call'
	from <internal:kernel>:187:in `loop'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:53:in `call'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:42:in `block in call'
2024-06-16 14:10:16 +0000 I [      info] missing: net-imap (net-imap-0.4.13)
```

I can verify that the gem _was_ successfully built and pushed: https://rubygems.org/gems/net-imap/versions/0.4.13

Ruby version: ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
Bundler version: "Using Bundler 2 shipped with ruby-3.3.1" (I think that was 2.5.9?)

Link to failed action: https://github.com/ruby/net-imap/actions/runs/9536527233/job/26283588269

### PR DESCRIPTION
**Pull request by iMacTia**
## Summary

A refactored `Bundler::CompactIndexClient::Cache` class was released in v2.5.12, causing issues with the now missing `dependencies` method: https://github.com/rubygems/rubygems/compare/bundler-v2.5.11...bundler-v2.5.12

The same functionality is now offered by a new `Bundler::CompactIndexClient::Parser` class, and nicely exposed via the `Bundler::CompactIndexClient#info` method.

Fixes #44

### CODE REVIEW

**Review by ccutrer — APPROVED** [review]
I've look through the sources of Bundler 2.5.11 and 2.5.12, and confirmed these two methods are equivalent (2.5.12 add an additional field to the info arrays, which is the name, but that should matter in this code)

File: lib/rubygems/await.rb [hunk 1]
```diff
@@ -262,7 +262,11 @@ def process_element(name, tuples)
                 "unsupported bundler version: #{Bundler::VERSION}. " \
                 "#{cic.class} does not respond to #info or #update_info"
         end
-        info = cic.instance_variable_get(:@cache).dependencies(name)
+        info = if defined?(::Bundler::CompactIndexClient::Parser)
+                 cic.info(name)
```
Comment (segiddins) [inline lib/rubygems/await.rb:266]: do we maybe need to clear a cache here now, or something?

Comment (iMacTia) [reply lib/rubygems/await.rb:266]: I don't think so. We weren't clearing it before so I don't believe we need to clear it now?

Comment (segiddins) [reply lib/rubygems/await.rb:266]: I think the caching is now at the level we are calling, whereas before we were calling into one level deeper

Comment (iMacTia) [reply lib/rubygems/await.rb:266]: I'm not sure I follow with my limited understanding of bundler internals I'm afraid 😞 
Happy to give it another look but I think I'll need a little nudge in the right direction
